import React from "react";
import { motion, motionValue } from "framer-motion";
import { SubmitHandler, useForm } from "react-hook-form";
import { SocailIcon } from "react-social-icons";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";
import classes from "../../styles/Contact.module.scss";

type Props = {};

export default function ContactUs(props: Props) {
  const [name, setName] = React.useState<string>("");
  const [email, setEmail] = React.useState<string>("");
  const [message, setMessage] = React.useState<string>("");
  const [sent, isSent] = React.useState<boolean>(false);
  const [error, setError] = React.useState<boolean>(false);

  const sendMail = async () => {
    // setError(false)
    // if (!name || !email) {
    //     setError(true)
    // } else {
    //     let templateParams = {
    //         from_name: name,
    //         from_email: email,
    //         message: message,
    //     }
    //     const mail = await emailjs
    //         .send(
    //             'service_pz9e3th',
    //             'template_nrpx7uj',
    //             templateParams,
    //             'bE7FBsdP5YFb4U6LK'
    //         )
    //         .then(() => isSent(true))
    // }
  };

  return (
    <React.Fragment>
      <Head>
        <title>StayBook - Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      <main className={`w-screen`}>
        <div className={classes.contactUsBody}>
          <Image
            src={"/background.jpg"}
            layout="fill"
            objectFit="cover"
            alt={"Staybook Hotels and Tours"}
          />
          <div className={classes.form}>
            <h1>Contact Us</h1>
            <p>
              Do you want to enquire about our pricing, current offers and
              arrangements we can help you with? Give us a call or send in your
              concerns through the form below.
            </p>
            <div className={classes.input}>
              <input
                value={name}
                onChange={(e) => setName(e.target.value)}
                type="text"
                style={{ marginRight: "1rem" }}
                placeholder="Name *"
              />

              <input
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                type="text"
                style={{ marginLeft: "1rem" }}
                placeholder="Email *"
              />
            </div>

            {error && <p className={classes.error}>Enter email and name</p>}

            <textarea
              value={message}
              onChange={(e) => setMessage(e.target.value)}
              placeholder="Message"
            />
            {!sent ? (
              <div onClick={sendMail} className={classes.button}>
                Submit
              </div>
            ) : (
              <a href="/" className={classes.button}>
                Done
              </a>
            )}
          </div>
        </div>
      </main>
    </React.Fragment>
  );
}
