import React from "react";
import Head from "next/head";
import AuthCard from "@/components/login/AuthCard";
import { groq } from "next-sanity";
import { sanityClient } from "@/sanity";
import { useRouter } from "next/router";

type Props = {
  imagesList: any[];
};

export default function Login(props: Props) {
  const router = useRouter();

  return (
    <React.Fragment>
      <Head>
        <title>StayBook - Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      <main
        className={`w-screen flex justify-center align-middle items-center`}
      >
        <AuthCard imagesList={props.imagesList} />
      </main>
    </React.Fragment>
  );
}

export const getStaticProps = async (context: any) => {
  const hotelImageListQuery = groq`
      *[_type == "hotel"] {
          name,
          "url":images[0].asset->url
      }
  `;

  const imagesList: any[] = await sanityClient.fetch(hotelImageListQuery);
  return {
    props: {
      imagesList,
    },
  };
};
function jwt_decode(arg0: string) {
  throw new Error("Function not implemented.");
}
