import React from "react";
import { motion, motionValue } from "framer-motion";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";

type Props = {};

export default function Policy(props: Props) {
  return (
    <React.Fragment>
      <Head>
        <title>StayBook - Policy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      <main>Policy</main>
    </React.Fragment>
  );
}
