import React from "react";
import { motion, motionValue } from "framer-motion";
import { SubmitHandler, useForm } from "react-hook-form";
import { SocailIcon } from "react-social-icons";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";
import { extractJWTValues } from "@/lib/helper";
import { useRouter } from "next/router";

type Props = {
  userDetails: any;
};

type Props = {
  userDetails: any;
};

export default function UserProfile(props: Props) {
  const router = useRouter();
  console.log(props.userDetails);

  return (
    <React.Fragment>
      <Head>
        <title>StayBook - Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      <main className={`w-screen`}>
        <motion.div className={`relative flex flex-col w-[90%] mt-10`}>
          <h1 className={`text-md font-normal`}>Profile</h1>
          <div className={`relative flex flex-row`}>
            <div className={`relative flex font-bold`}>
              {props.userDetails.User_Display_Name}
            </div>
            <div className={`relative flex`}>
              {props.userDetails.user_Email_Id}.
            </div>
            <div className={`relative flex underline font-semibold`}>
              Go to Profile
            </div>
          </div>
        </motion.div>
      </main>
    </React.Fragment>
  );
}

export async function getServerSideProps(context: any) {
  const { req, res } = context;
  const cookies = parse(req.headers.cookie || "");
  const userAccessToken = cookies[USER_ACCESS_TOKEN];
  const userAccessTokenObject = await extractJWTValues(userAccessToken);
  const userCollectionDoc = await getUserProfileDetails(userAccessTokenObject);
  // console.log(userCollectionDoc);
  return {
    props: {
      userDetails: userCollectionDoc,
    },
  };
}
