import React from "react";
import Head from "next/head";
import Image from "next/image";
// import { Inter } from "next/font/google";
// import styles from "@/styles/Home.module.css";
import { groq } from "next-sanity";
import { Amenity, Hotel, HotelGroup, Post, TourPackage } from "@/typings";
import { GetStaticProps } from "next/types";
import { fetchAmenities } from "@/utils/fetchAmenities";
import { sanityClient } from "@/sanity";

import HotelCarousel from "@/components/hotelsSlideView/HotelCarousel";
import ToursAndTravels from "@/components/screens/home/ToursAndTravels";
import SpeacialOffers from "@/components/screens/home/SpecialOffers";

type Props = {
  hotelsList: any[],
};

export default function Home(props: Props) {

  return (
    <React.Fragment>
      <Head>
        <title>StayBook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      <main>
        <HotelCarousel hotelsList={props.hotelsList} />
        <ToursAndTravels />
        <SpeacialOffers />
      </main>
    </React.Fragment>
  );
}

export const getStaticProps = async () => {
  const hotelsListQuery = groq`
    *[_type == "hotel"] | order(order asc) {
      "hotel_Name":name,
      _id,
      "hotel_Id":id,
      description,
      images[]{
        "image_Url":asset->url,
      }[0...2],
      "slug_Name": slug{current},
    }
  `;

  const hotelsList: any[] = await sanityClient.fetch(hotelsListQuery);
  return {
    props: {
      hotelsList,
    }
  }
}