import React from "react";
import { motion, motionValue } from "framer-motion";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";
import { useRouter } from "next/router";
import { sanityClient } from "@/sanity";
import { groq } from "next-sanity";
import moment from "moment";
import { BookingDetails } from "@/classModels/bookings/bookingDetails";
import { getBookedHotelDetails } from "@/lib/booking/bookingHandler";

type Props = {
  userBooking: BookingDetails;
};

export default function BookingInformation(props: Props) {
  const router = useRouter();
  const [hotelName, setHotelName] = React.useState<string>("");
  const [userBookingId, setUserBookingId] = React.useState<string>("");
  const [userName, setUserName] = React.useState<string>("");
  const [userPhoneNumber, setUserPhoneNumber] = React.useState<string>("");
  const [userEmailId, setUserEmailId] = React.useState<string>("");

  console.log(router);
  React.useEffect(() => {
    setHotelName(String(router.query.hotel_Name));
    // setUserBookingId(String(router.params.bookingId));
    setUserName(String(router.query.user_Name));
    setUserPhoneNumber(String(router.query.user_Phone));
    setUserEmailId(String(router.query.user_Email));
  }, [
    router.query.bookingId,
    router.query.hotel_Name,
    router.query.user_Email,
    router.query.user_Name,
    router.query.user_Phone,
  ]);

  return (
    <React.Fragment>
      <Head>
        <title>Booking Successful</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      <main className={`w-screen`}>
        <motion.div className={`relative w-[90%] flex flex-col mx-auto`}>
          <motion.div
            className={`relative flex w-full justify-center align-middle items-center mx-auto my-5`}
          >
            <h1 className={`text-center font-bold font-serif text-4xl`}>
              Your room has been successfully booked.
            </h1>
          </motion.div>
          <motion.div className={`relative flex flex-col w-full`}>
            <motion.div
              className={`relative flex flex-col w-full rounded-md p-2 my-2`}
            >
              <motion.div
                className={`relative flex font-sans font-semibold text-3xl`}
              >
                {"Hotel Name"}
              </motion.div>
              <motion.div className={`relative flex text-lg text-gray-500`}>
                {props.userBooking.hotel_Name}
              </motion.div>
            </motion.div>
            <motion.div
              className={`relative flex flex-col w-full rounded-md p-2 my-2`}
            >
              <motion.div
                className={`relative flex font-sans font-semibold text-3xl`}
              >
                {"User Name"}
              </motion.div>
              <motion.div className={`relative flex text-lg text-gray-500`}>
                {props.userBooking.user_Name}
              </motion.div>
            </motion.div>
            <motion.div
              className={`relative flex flex-col w-full rounded-md p-2 my-2`}
            >
              <motion.div
                className={`relative flex font-sans font-semibold text-3xl`}
              >
                {"User Phone Number"}
              </motion.div>
              <motion.div className={`relative flex text-lg text-gray-500`}>
                {props.userBooking.user_Phone_Number}
              </motion.div>
            </motion.div>
            <motion.div
              className={`relative flex flex-col w-full rounded-md p-2 my-2`}
            >
              <motion.div
                className={`relative flex font-sans font-semibold text-3xl`}
              >
                {"User Email Id"}
              </motion.div>
              <motion.div className={`relative flex text-lg text-gray-500`}>
                {props.userBooking.user_Email_Id}
              </motion.div>
            </motion.div>
            <motion.div
              className={`relative flex flex-col w-full rounded-md p-2 my-2`}
            >
              <motion.div
                className={`relative flex font-sans font-semibold text-3xl`}
              >
                {"Check-In Date"}
              </motion.div>
              <motion.div className={`relative flex text-lg text-gray-500`}>
                {/* {props.userBooking.checkin_Time.toString()} */}
              </motion.div>
            </motion.div>
            <motion.div
              className={`relative flex flex-col w-full rounded-md p-2 my-2`}
            >
              <motion.div
                className={`relative flex font-sans font-semibold text-3xl`}
              >
                {"Check-Out Date"}
              </motion.div>
              <motion.div className={`relative flex text-lg text-gray-500`}>
                {/* {props.userBooking.checkout_Time.toString()} */}
              </motion.div>
            </motion.div>
            <motion.div
              className={`relative flex flex-col w-full rounded-md p-2 my-2`}
            >
              <motion.div
                className={`relative flex font-sans font-semibold text-3xl`}
              >
                {"Total Rooms Booked"}
              </motion.div>
              <motion.div className={`relative flex text-lg text-gray-500`}>
                {props.userBooking.total_Rooms_Count}
              </motion.div>
            </motion.div>
            <motion.div
              className={`relative flex flex-col w-full rounded-md p-2 my-2`}
            >
              <motion.div
                className={`relative flex font-sans font-semibold text-3xl`}
              >
                {"Receipt Id"}
              </motion.div>
              <motion.div className={`relative flex text-lg text-gray-500`}>
                {props.userBooking.receipt_Id}
              </motion.div>
            </motion.div>
            <motion.div
              className={`relative flex flex-col w-full rounded-md p-2 my-2`}
            >
              <motion.div
                className={`relative flex font-sans font-semibold text-3xl`}
              >
                {"Total Amount"}
              </motion.div>
              <motion.div className={`relative flex text-lg text-gray-500`}>
                {props.userBooking.total_Price}
              </motion.div>
            </motion.div>
            <motion.div
              className={`relative flex flex-col w-full rounded-md p-2 my-2`}
            >
              <motion.div
                className={`relative flex font-sans font-semibold text-3xl`}
              >
                {"Amount Paid"}
              </motion.div>
              <motion.div className={`relative flex text-lg text-gray-500`}>
                {/* {props.userBooking.amount_Paid.toFixed(2)} */}
              </motion.div>
            </motion.div>
            <motion.div
              className={`relative flex flex-col mt-5 align-middle items-center mx-auto`}
            >
              <button
                onClick={() => {
                  router.push({ pathname: "/profile/my-bookings" });
                }}
                className={`px-6 py-3 rounded-full font-medium text-lg bg-gray-300 hover:bg-gray-400`}
              >
                Go to Profile
              </button>
              <p className={`my-3 text-gray-500`}>
                View your booking by logging-in to your account.
              </p>
            </motion.div>
          </motion.div>
        </motion.div>
      </main>
    </React.Fragment>
  );
}

export async function getServerSideProps(context: any) {
  const { params, query, req, res } = await context;

  const userEmailId = query.user_Email;
  const booking_Id = params.bookingId;

  const userBooking = await getBookedHotelDetails(userEmailId, booking_Id);

  return {
    props: {
      userBooking: JSON.parse(userBooking),
    },
  };
}
