import React from "react";
import { motion, motionValue } from "framer-motion";
import { SubmitHandler, useForm } from "react-hook-form";
import { SocailIcon } from "react-social-icons";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";
import { extractJWTValues } from "@/lib/helper";
import { useRouter } from "next/router";

type Props = {
  userDetails: any;
};

export default function HotelBookings(props: Props) {
  return (
    <React.Fragment>
      <Head>
        <title>Hotel Bookings</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      <main className={`w-screen flex flex-col items-center`}>
        <motion.div className={`relative flex w-[90%] mt-10`}>
          <h1 className={`text-md font-normal`}>
            Profile &nbsp;＞&nbsp; My Bookings
          </h1>
        </motion.div>
        <motion.div className={`relative flex w-[90%] mt-3`}>
          <h1 className={`text-4xl font-bold`}>My Bookings</h1>
        </motion.div>
        <motion.div
          className={`relative flex flex-col space-y-8 w-[90%] mt-16`}
        ></motion.div>
      </main>
    </React.Fragment>
  );
}

// export async function getServerSideProps(context: any) {
//   const { req, res } = context;
//   const cookies = parse(req.headers.cookie || "");
//   const userAccessToken = cookies[USER_ACCESS_TOKEN];
//   const userAccessTokenObject = await extractJWTValues(userAccessToken);
//   const userCollectionDoc = await getUserProfileDetails(userAccessTokenObject);
//   // console.log(userCollectionDoc);
//   return {
//     props: {
//       userDetails: userCollectionDoc,
//     },
//   };
// }