import React from "react";
import { motion, motionValue } from "framer-motion";
import { SubmitHandler, useForm } from "react-hook-form";
import { SocailIcon } from "react-social-icons";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";
import { groq } from "next-sanity";
import { sanityClient } from "@/sanity";

type Props = {
  packagesList: any[];
};

export default function TourPackages(props: Props) {
  return (
    <React.Fragment>
      <Head>
        <title>StayBook Tour Packages</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      <main className={`w-screen`}>
        <motion.div className={`relative w-full mt-3 mb-6`}>
          <h1 className={`text-center font-serif text-6xl`}>Tour Packages</h1>
        </motion.div>
      </main>
    </React.Fragment>
  );
}

export const getStaticProps = async (context: any) => {
  const packageQuery = groq`
    *[_type == "package"] {
      _id,
      name,
      time,
      description,
      highlight,
      "image_Url":image.asset->url,
    }
  `;

  const packagesList: any[] = await sanityClient.fetch(packageQuery);
  return {
    props: {
      packagesList,
    },
  };
};
