import React from "react";
import { motion, motionValue } from "framer-motion";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";
import { extractJWTValues } from "@/lib/helper";
import { useRouter } from "next/router";

import {
  getMonth,
  hotelPriceRangeMatrix,
} from "@/lib/calendar/calendarHandler";
import { Calendar } from "react-date-range";

import CalendarHeader from "@/components/calendar/CalendarHeader";
import CalendarSidebar from "@/components/calendar/Sidebar";
import CalendarMonth from "@/components/calendar/Month";

type Props = {
  userDetails: any;
};

export default function HotelPriceCalendar(props: Props) {
  const [selectedDate, setSelectedDate] = React.useState<Date>(new Date());
  const [currentMonth, setCurrentMonth] = React.useState(getMonth());
  const [pricePlannerMatrix, setPricePlannerMatrix] = React.useState<any>(
    hotelPriceRangeMatrix
  );
  const [showEventModal, setShowEventModal] = React.useState<boolean>(false);

  // const fetchHotelPrices = async () => {
  //   const hotelName = "";
  //   const response = await fetch("/api/calendar/fetchHotelPrices", {
  //     method: "POST",
  //     body: JSON.stringify({ hotelName }),
  //     headers: {
  //       "Content-Type": "application/json",
  //     },
  //   });

  //   const data = await response.json();
  //   console.log("API Handler Function");
  //   console.log(data);
  //   return data;
  // };

  return (
    <React.Fragment>
      <Head>
        <title>StayBook - Hotel Calendar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      <main
        className={`w-screen flex justify-center align-middle items-center`}
      >
        {/* <button onClick={fetchHotelPrices}>fetch</button> */}

        <div className="relative h-full w-[97.5%] flex flex-col justify-start">
          <CalendarHeader
            selectedDate={selectedDate}
            setSelectedDate={setSelectedDate}
            currentMonth={currentMonth}
            setCurrentMonth={setCurrentMonth}
          />
          <div className="flex flex-1">
            <CalendarSidebar
              selectedDate={selectedDate}
              setSelectedDate={setSelectedDate}
              currentMonth={currentMonth}
              setCurrentMonth={setCurrentMonth}
            />
            <CalendarMonth
              month={currentMonth}
              pricePlannerMatrix={pricePlannerMatrix}
              showEventModal={showEventModal}
              setShowEventModal={setShowEventModal}
            />
          </div>
        </div>
      </main>
    </React.Fragment>
  );
}
